### PR TITLE
fix(isr): use modifyGeneratedHtml in all cache generation process

### PR DESCRIPTION
**Pull request by maxisam**
fix: #1742 #1758 

- move modifyGeneratedHtml to ISRHandlerConfig
- consolidate cache generation related code
- serve existing cache first instead of waiting regeneration
- create example to show modifyGeneratedHtml in demo

Feel free to make any suggestion. Thanks!

### CODE REVIEW

**Comment by maxisam** [comment]
Trying my best to remove unrelated changes but the lint just keep adding "," back. I hope it is not too hard to review with those changes.

**Review by eneajaho — APPROVED** [review]
This cleanup was really needed! Thank you!! Amazing job!

**Comment by eneajaho** [comment]
@maxisam 
A rebase is needed. Then we can merge 🎉

**Comment by maxisam** [comment]
> @maxisam A rebase is needed. Then we can merge 🎉

Do you mean you prefer to rewrite some commits and force push it? I usually don't do that since I use squash merge in general.

However, if you prefer to keep some meaningful commits, I can rebase it and force push

**Comment by hoebbelsB** [comment]
we are generating the changelog from the commit messages. In best case they are meaningful and we don't have to squash. However, it's also possible. If we can fit your efforts into one meaningful commit message, it should also be fine. Wdyt @eneajaho ?

**Comment by eneajaho** [comment]
This PR was breaking, so I will merge this other one too (https://github.com/rx-angular/rx-angular/pull/1766) so we can release these new features in a minor instead of having to release a major version. 

Basically the devs can configure the modify fn in two places and in the next major we can remove the one in the render config.

**Pull request merged**
