### PR TITLE
Remove deprecated APIs

### PR DESCRIPTION
**Pull request by edbzn**
- Drop global render-strategy (cdk)
- Drop transformations and selections in the main entry-point (state)
- Drop zone-less/rxjs wrappers (cdk)

### CODE REVIEW

**Review by hoebbelsB — COMMENTED** [review]
@edbzn thx for the PR. the changes look good. I just want to mention some things.
We should check that if the updated unit tests in the base branch should be moved to https://github.com/rx-angular/rxjs-zone-less. This is also true for any deleted documentation.

Also, should we provide a migration script for deprecations that can be replaced with other paths ?

**Comment by edbzn** [comment]
> We should check that if the updated unit tests in the base branch should be moved to https://github.com/rx-angular/rxjs-zone-less. This is also true for any deleted documentation.

@hoebbelsB I'm not sure to get what you mean, should the updated tests from this PR #1509 be backported to https://github.com/rx-angular/rxjs-zone-less?

> Also, should we provide a migration script for deprecations that can be replaced with other paths ?

The migration already exist and was provided for state v1.4.7:

```typescript
const renames: Record<string, string | [string, string]> = {
  createSideEffectObservable: '@rx-angular/state/selections',
  createAccumulationObservable: '@rx-angular/state/selections',
  select: '@rx-angular/state/selections',
  stateful: '@rx-angular/state/selections',
  distinctUntilSomeChanged: '@rx-angular/state/selections',
  selectSlice: '@rx-angular/state/selections',
  KeyCompareMap: '@rx-angular/state/selections',
  CompareFn: '@rx-angular/state/selections',
  PickSlice: '@rx-angular/state/selections',
  insert: '@rx-angular/cdk/transformations',
  remove: '@rx-angular/cdk/transformations',
  toDictionary: '@rx-angular/cdk/transformations',
  update: '@rx-angular/cdk/transformations',
  extract: '@rx-angular/cdk/transformations',
  upsert: '@rx-angular/cdk/transformations',
  setProp: '@rx-angular/cdk/transformations',
  patch: '@rx-angular/cdk/transformations',
  deleteProp: '@rx-angular/cdk/transformations',
  dictionaryToArray: '@rx-angular/cdk/transformations',
  toggle: '@rx-angular/cdk/transformations',
  slice: '@rx-angular/cdk/transformations',
  RxState: '@rx-angular/state',
};
```

**Comment by hoebbelsB** [comment]
@edbzn 

> I'm not sure to get what you mean, should the updated tests from this PR https://github.com/rx-angular/rx-angular/pull/1509 be backported to https://github.com/rx-angular/rxjs-zone-less? Because there's nothing new in the base branch regarding rxjs-zone-less.

Yes, I mean backporting the updated tests

> The migration already exist and was provided for state v1.4.7:

Great, should we change it to run again with the next version?

**Comment by hoebbelsB** [comment]
@edbzn moved the tests: https://github.com/rx-angular/rxjs-zone-less/pull/7

**Pull request merged**
