### PR TITLE
fix(template): fix possibly undefined `_virtualItems` in autosize and dynamic strategies

### LINKED ISSUE #1744: Virtual scroll: Resetting items to an array smaller than currently rendered range results in component crash
# Description

When a virtual scroll has items and is not scrolled to the top, and items get reset to an array smaller than currently rendered, a TypeError is thrown, making a component unusable.

The issue is observed for autosize and dynamic strategies - fixed strategy seems to work just fine.

```
TypeError: Cannot read properties of undefined (reading 'size')
    at _AutoSizeVirtualScrollStrategy.getItemSize (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1942:38)
    at _AutoSizeVirtualScrollStrategy.calcAnchorScrollTop (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1907:36)
    at Object.next (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1620:14)
```

# Steps to Reproduce the Issue

## Reset to empty array

**See stackblitz:**

- [dynamic strategy](https://stackblitz.com/edit/stackblitz-starters-ggjmb8?file=src%2Fmain.ts)
- [autosize strategy](https://stackblitz.com/edit/stackblitz-starters-435szr?file=src%2Fmain.ts)

**Steps:**

1. Enter page
2. Scroll (or click on the "scroll to 100" button)
3. Click on the "reset items" button

**Expected behavior:**

Virtual scroll works just fine and scrolls to the top

**Actual behavior:**

TypeError is thrown and a component is unusable.

## New items array is smaller

It is possible to encounter the issue when new items array is smaller than currently rendered range. See [this stackblitz](https://stackblitz.com/edit/stackblitz-starters-bsuszv?file=src%2Fmain.ts) and follow reproduction steps:

1. Enter page
2. Scroll to the bottom (or click on the "scroll to 5" button)
3. Click on the "set to 1 item" button

**Expected behavior:**

Virtual scroll works just fine and scrolls to the top

**Actual behavior:**

TypeError is thrown and a component is unusable.

# Environment

@rx-angular/template 17+ . Stackblitz has version 18, but in our codebase we observe the same issue with rx-angular version 17.

# Notes

`getItemSize` throws, when an `_virtualItems` array is empty, or an `index` is out of bounds. First part to fix it is probably to add an optional operator. Another part is calling `getItemSize` when `index` is definitely not present there, but I'm not sure how you want to tackle that.

```ts
  getItemSize(index) {
    return this._virtualItems[index]?.size || this.tombstoneSize;
  }
```

### PR DESCRIPTION
**Pull request by rozpuszczalny**
Fixes #1744. See that issue to find out the steps to reproduce the problem.

If merged, please make sure to also release fix versions for rx-angular 17.x

### CODE REVIEW

**Comment by hoebbelsB** [comment]
thank u for the contribution, I will come back to you soon with a review

**Comment by rozpuszczalny** [comment]
Thanks! I just want to point out rx-angular's virtual scroll improved our app's performance tremendously and I am greatful for that library to exists 🙌

Just to note, even with these null checks in place a component still can go into similar issue (I've not added null checks for every single `_virtualItems[index]`), so maybe it should be fixed differently, e.g. by not adding null checks, but rather by not going into that state in the first place.

However, the relations in the code are quite complicated and I didn't want to dig too deep with it (so I don't break other things in the process 😉).

**Comment by hoebbelsB** [comment]
> Thanks! I just want to point out rx-angular's virtual scroll improved our app's performance tremendously and I am greatful for that library to exists 🙌

🥰

> so maybe it should be fixed differently, e.g. by not adding null checks, but rather by not going into that state in the first place.

Exactly what I was also thinking, good that you've pointed it out!

**Comment by hoebbelsB** [comment]
hello @rozpuszczalny I hope you don't mind to close this PR in favor of https://github.com/rx-angular/rx-angular/pull/1747. Of course i'd like to hear your feedback on that new PR. Would be cool if you could confirm it'll solve your issue.

Also thank you again for the kind words your contribution ✊ Really appreciated!

**Pull request closed without merging**
