### PR TITLE
fix(state): exclude `undefined` from return type of `stateful`

### LINKED ISSUE #837: Provide ensured type for `stateful` operator
# Problem Solved By The Feature

Improved typings

# Solution

Even if `stateful` operator filtering all empty values, it still returns `T | undefined` type and it leads to doublecheck

Screenshot 2021-07-09 at 15 08 25

### PR DESCRIPTION
**Pull request by niklaas**
Fixes #837.

This should fix the typing for `#stateful` to no longer include `undefined`.

I am not sure what to do about the declaration and definition of `#stateful` in `app/demos/src` though..? I changed the one in `libs/state/src`.

https://github.com/rx-angular/rx-angular/blob/cbd921df0b7eebd56b4b3cb6428a825fd6bb8acb/apps/demos/src/app/rx-angular-pocs/cdk/utils/rxjs/operators/stateful.ts#L47

### CODE REVIEW

**Review by edbzn — APPROVED** [review]
Great! The inference was not doing its job?

**Comment by niklaas** [comment]
> Great! The inference was not doing its job?

Nope, unfortunately `#filter` doesn't do this properly.

Just saw that tests are failing though. Will get back to these within the next days...

**Comment by niklaas** [comment]
Well, obviously, `stateful` no longer is a `MonoTypeOperatorFunction` now... Tests should pass now.

**Comment by niklaas** [comment]
@BioPhoton @edbzn resolved the merge conflicts. Something more you need? :)

**Comment by edbzn** [comment]
Looks like my recent refactor of the GitHub actions break contributions. I will investigate asap. Besides that the code LGTM!

**Comment by niklaas** [comment]
@BioPhoton @edbzn just spotted this in my GH notifications. Is this still relevant / an improvement?

**Comment by BioPhoton** [comment]
@niklaas Yes it is!

We just discussed this one! I'm sry is is so slow here! 🙏

**Comment by twittwer** [comment]
Did the discussion come to a conclusion?

**Comment by edbzn** [comment]
There are conflicts now, but I think we can resolve them and merge, what do you think @hoebbelsB?

**Comment by hoebbelsB** [comment]
@edbzn go ahead and lets merge it!

**Pull request merged**
