### PR TITLE
feat: upgrade to angular 19

### PR DESCRIPTION
**Pull request by hoebbelsB**
* [x] upgraded to latest angular version
* [x] bumped peerDependencies
* [x] waiting for https://github.com/rx-angular/rx-angular/pull/1805 to get merged, as it's a fork of it

### CODE REVIEW

**Review by edbzn — APPROVED** [review]

**Comment by hoebbelsB** [comment]
need to fix the tests that are broken because of standalone default ^^

**Comment by hoebbelsB** [comment]
> This PR is blocked by Nx support for Angular v19 and ng-packagr changes which occurred in v19 version that updates the whole stylesheet story in ng-packagr.
> 
> The project compiles fine if we use ng-packagr directly:
> 
> ```json
>  "build-virtual-scrolling" : {
>       "executor": "@angular-devkit/build-angular:ng-packagr",
>       "options": {
>         "project": "libs/template/ng-package.json"
>       },
>       "configurations": {
>         "production": {
>           "tsConfig": "libs/template/tsconfig.lib.json"
>         },
>         "development": {
>           "tsConfig": "libs/template/tsconfig.lib.json"
>         }
>       },
>       "defaultConfiguration": "production"
>     },
> ```

@eneajaho  can't we just do that?

**Comment by bitrxjs** [comment]
any dates for v19 release?

**Comment by hoebbelsB** [comment]
we can make the build work somehow, however - the component tests are failing, due to some cypress incompatibilities with angular v19... i'm thinking about a way how to solve it

**Review by edbzn — APPROVED** [review]
LGTM

**Comment by tanjadev** [comment]
:shipit:

**Pull request merged**
