### PR TITLE
Update local-variables.md to include `*ngIf="num$ as n"`

### PR DESCRIPTION
**Pull request by Sefibrah**
[This part of docs](https://www.rx-angular.io/docs/template/concepts/local-variables) was unclear to me (at first glance). 

My suggestion is to include `*ngIf="num$ as n"`.

It's minuscule, but probably worth it for the _clarity_ 🤌

Am I overthinking this?

### CODE REVIEW

**Comment by edbzn** [comment]
Hey @Sefibrah, thanks for the change. Could you run `yarn nx format:write --base=HEAD^` and format the commit message like `docs: update ...`, please?

**Comment by Sefibrah** [comment]
Ok, I'll try and do it ASAP...

**Comment by Laurens-makel** [comment]
Just my 2 cents, the docs state `Both ways can reduce the usage of pipes the async pipe (or any other pipe).`.

This seems a little odd since `<ng-container *ngIf="num$ as n"> {{ n | async }} {{ n | async}} {{ n | async}} </ng-container>` could also be re-written to a single usage of async `<ng-container *ngIf="num$ | async as n"> {{ n }} {{ n }} {{ n }} </ng-container>`.

However this does have a drawback when the observable returns falsy values, which does not happen with the first approach, however the docs do not mention anything about this.

**Comment by hoebbelsB** [comment]
@Sefibrah do you want to add anything else to this PR or is it ready to be merged?

**Comment by Sefibrah** [comment]
Not really, just the aforementioned thing above, but I have no time for it...

**Comment by hoebbelsB** [comment]
could u rebase the branch to make the pipeline green?

**Pull request merged**
