### PR TITLE
fix(cdk): make sure tasks queued by NgZone are also executed

### PR DESCRIPTION
**Pull request by hoebbelsB**
# Description

closing #1385 

as described in the linked issue, the scheduler was missing tasks added to the queue by NgZone. This PR fixes that behavior and makes sure we are not missing out cd events.

* [x] fix missing cd
* [x] add unit test

### CODE REVIEW

**Review by Karnaukhov-kh — APPROVED** [review]

**Review by edbzn — COMMENTED** [review]
That would be nice to test the rendering with the scheduler through components to cover this type of scenario, @hoebbelsB do you think the bug is easily replicable within a Cypress Component test?

**Comment by twittwer** [comment]
Can I help to finalize this?  
Should I simplify the reproduction as much as possible, to maybe use it for component test?

**Comment by twittwer** [comment]
@hoebbelsB @Karnaukhov-kh @edbzn 
What is required to get PR merged and released?
I would like to help if possible.
We would be really happy to see this released 🙏, as we are stuck at Angular < 14.2 because of this problem.

**Comment by hoebbelsB** [comment]
@twittwer sorry for taking so long! I will take a look this week :pray:

**Comment by hoebbelsB** [comment]
@twittwer as promised, provided unit tests. The PR can be merged I think. @edbzn can u review again? If possible merge and release as well :partying_face:

**Review by edbzn — APPROVED** [review]

**Comment by twittwer** [comment]
@hoebbelsB Thank you very much, what a nice christmas present 🙏
I wish you a happy holiday 🎄

**Pull request merged**
