### PR TITLE
chore(docs): fix broken documentation links

### PR DESCRIPTION
**Pull request by ChristopherPHolder**

### CODE REVIEW

**Comment by ChristopherPHolder** [comment]
Their links are also broken but do not have a clear path to fixing: 

1. https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/cdk/zone-configurations/how-to-setup-zone-flags.md?plain=1#L43
2. https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/cdk/zone-less/_docs.md?plain=1#L4
3. https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/state/effects/_docs.md?plain=1#L4
4. https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/template/concepts/performance-issues.md?plain=1#L78
5. https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/libs/cdk/template/README.md?plain=1#L34
6. https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/libs/cdk/template/README.md?plain=1#L35
7. https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/libs/cdk/zone-configurations/README.md?plain=1#L36
8. https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/libs/cdk/zone-less/README.md?plain=1#L22

**Comment by LayZeeDK** [comment]
@ChristopherPHolder, please ask @BioPhoton about 1, 2, 3, and 8.

> Their links are also broken but do not have a clear path to fixing:
> 
> 1 https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/cdk/zone-configurations/how-to-setup-zone-flags.md?plain=1#L43
> 2 https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/cdk/zone-less/_docs.md?plain=1#L4
> 3 https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/state/effects/_docs.md?plain=1#L4
> 8 https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/libs/cdk/zone-less/README.md?plain=1#L22

**Review by LayZeeDK — COMMENTED** [review]
@ChristopherPHolder, please ask @BioPhoton about 1, 2, 3, and 8.

> Their links are also broken but do not have a clear path to fixing:
> 
> 1 https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/cdk/zone-configurations/how-to-setup-zone-flags.md?plain=1#L43
> 2 https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/cdk/zone-less/_docs.md?plain=1#L4
> 3 https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/apps/docs/docs/state/effects/_docs.md?plain=1#L4
> 8 https://github.com/rx-angular/rx-angular/blob/b0630f69017cc1871d093e976006066d5f2005b9/libs/cdk/zone-less/README.md?plain=1#L22

**Comment by BioPhoton** [comment]
I would just delete all stackblitz links.

**Comment by ChristopherPHolder** [comment]
> I would just delete all stackblitz links.

Link 1 is from stackblitz, the rest are from GitHub. 

Example 2:
 - [GitHub](https://github.com/BioPhoton/rx-angular-cdk-zone-less)
 
 Should those also be deleted? Or do you know where we can find the example projects @BioPhoton

**Comment by BioPhoton** [comment]
We don’t really have example projects for them this es where just empty setups

**Pull request merged**
