### PR TITLE
refactor(isr): eslint issues

### PR DESCRIPTION
**Pull request by maxisam**
I ran this locally, everything seems working fine. This will be the end of refactoring for IRS. I plan to add more features to my fork, and I will make a PR if you want

### CODE REVIEW

**Comment by maxisam** [comment]
I have no clue about the build error, might need you guys help on this Thx!

**Comment by eneajaho** [comment]
Thanks @maxisam. 
I will be working on getting all your PRs merged ❤️!

**Comment by maxisam** [comment]
Thanks man, sorry about making so many changes. Your code base is really good and we have a similar thing I created for our company, so I hope we can join forces for this  😊 Have a nice weekend

**Comment by maxisam** [comment]
also, I am on a camping trip with my family, so I might be slow to respond.

**Pull request merged**
