### PR TITLE
fix(transformation-helpers): log warning only if source is not empty.

### PR DESCRIPTION
**Pull request by Karnaukhov-kh**
Empty array considered as valid input for `toDictionary` helper. So there should be no warning about unexpected input.

thx @hoebbelsB

### CODE REVIEW

**Review by hoebbelsB — APPROVED** [review]
nice finding and thx for fixing it. looks fine for me. Do you think there is any way of testing if this additional if is causing the performance to decrease?

**Comment by hoebbelsB** [comment]
can you fix the failing checks?

**Comment by Karnaukhov-kh** [comment]
> nice finding and thx for fixing it. looks fine for me. Do you think there is any way of testing if this additional if is causing the performance to decrease?

Sure, will test today

> can you fix the failing checks?

Yup

**Comment by Karnaukhov-kh** [comment]
@hoebbelsB looks like no big difference in performance. Tested on a huge amount of data (300.000 elements). `performance.now()` approach.

image

About errors - you or Michael already fixed it, so I just merged master to this branch 😄.

**Pull request merged**
