### PR TITLE
Migrate to eslint

### PR DESCRIPTION
**Pull request by edbzn**
- remove tslint
- remove tslint comments
- configure eslint (for state, template and cdk)
- setup boundaries rules

### CODE REVIEW

**Comment by hoebbelsB** [comment]
hi @edbzn BIG THX! we need that desperately. Did u notice there is also another PR doing the same thing? There are just a couple of things left. Maybe we can connect those two together? https://github.com/rx-angular/rx-angular/pull/980

**Comment by BioPhoton** [comment]
Yes lets see to get that PR in. It looks good already got feedback and is a nice contribution. ❤

**Comment by edbzn** [comment]
@BioPhoton @hoebbelsB all rules have been added, I put some `@todo` in the code because some rules fail for the directive (rxFor and ViewportPrio). There's an issue with the Nx cache and build dependencies, I had to disable it for the build step. Will report the problem to Nx.

**Comment by edbzn** [comment]
Close in favor of #1086

**Pull request closed without merging**
