### PR TITLE
chore(ci): remove --head + add --frozen-install arguments

### PR DESCRIPTION
**Pull request by edbzn**
Following [this comment](https://github.com/rx-angular/rx-angular/pull/587#issuecomment-795698445) fix the undefined ref for master push Github action event.

PS need to be rebased after #587 because actually the lockfile is not in sync with master.

### CODE REVIEW

**Comment by hoebbelsB** [comment]
how is this one connected to https://github.com/rx-angular/rx-angular/pull/611 ? they both touch the same command

**Comment by edbzn** [comment]
@hoebbelsB I would suggest to update #611 changes with `--frozen-lockfile` option instead of `--pure-lockfile` to fail if package.json is not synced with lock file, then merge #611, and I will rebase to only include head comparison fix.

**Comment by hoebbelsB** [comment]
@edbzn thx for feedback! lets bring @arturovt to the discussion as well :) maybe he has some thoughts about this as well. I think your suggestion sounds very valid

**Comment by arturovt** [comment]
Let’s merge this one and then I’ll update my command to use the frozen lock file!

**Comment by edbzn** [comment]
Schematics fixes are not related, we can merge these changes separately, whatever you or me, someone will need to rebase! :smile:

**Comment by arturovt** [comment]
Ah, great. I was thinking that schematics are related because you mentioned that PR in the description :slightly_smiling_face: 

@hoebbelsB bump fire! :smile:

**Comment by hoebbelsB** [comment]
@edbzn can u fix the conflict? we can merge afterwards

**Comment by edbzn** [comment]
@hoebbelsB done

**Review by hoebbelsB — APPROVED** [review]

**Pull request merged**
