### PR TITLE
fix(template): use correct CdRef instance in RxPush

### PR DESCRIPTION
**Pull request by hoebbelsB**
# Description

as elaborated in #1606 , using the `inject` method in pipes is causing them to use the ChildComponents CdRef. This is a problem for `RxPush`, as `detectChanges` won't update input bindings.

### CODE REVIEW

**Comment by edbzn** [comment]
I think we have to check if this won't produce any problem related to [useDefineForClassFields](https://angular.schule/blog/2022-11-use-define-for-class-fields) tsc option (the reason why we introduced inject at the first place). One question also, what if we use { skipSelf: true } flag for the inject fn instead of constructor DI?

**Comment by edbzn** [comment]
So I tried, and the option skipSelf doesn't fix the issue. However it seems that the wrong behavior comes from the constructor injection, not the inject function, cf [this comment](https://github.com/angular/angular/issues/50952#issuecomment-1622415512). I would like to have feedback from the Angular team before merging this. Do you mind creating an issue @hoebbelsB?

**Comment by hoebbelsB** [comment]
Should we still ship it as hotfix as is now? The pipeline doesn't seem to have issues, what would you like to check about [useDefineForClassFields](https://angular.schule/blog/2022-11-use-define-for-class-fields) ?

@alxhub also told me he is already aware of that issue and he knows how to fix it

**Review by edbzn — APPROVED** [review]

**Comment by bryanforbes** [comment]
Is there any chance a backport could be done for the 16.x versions?

**Comment by hoebbelsB** [comment]
@bryanforbes yes, going to ship it this weekend

**Pull request merged**
