### PR TITLE
use concatMap, not switchMap to avoid loosing deletes

### PR DESCRIPTION
**Pull request by datumgeek**

### CODE REVIEW

**Comment by BioPhoton** [comment]
Good catch!!

**Comment by datumgeek** [comment]
@BioPhoton - can you help with this?

> Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate. Alternatively, an individual PR can be opted-in with a maintainer adding the "hacktoberfest-accepted" label to the PR.

**Comment by BioPhoton** [comment]
I added the label. Is this OK?

**Comment by edbzn** [comment]
@BioPhoton I think there's other places where this change should belong (demos and docs). Also, what about adding a note about `RxState#hold` and lossy operators? I think many people will use `switchMap` by default as I did.

**Pull request merged**
