### PR TITLE
chore: migrate to eslint

### PR DESCRIPTION
**Pull request by NileshPatel17**
@hoebbelsB This PR addresses #975 

Following Projects migrated:
1. cdk
2. state
3. template

Please let me know if this can be merged.

### CODE REVIEW

**Comment by hoebbelsB** [comment]
also it looks like we've got a problem with our CI which we have to fix asap ^^

**Comment by Karnaukhov-kh** [comment]
Hi @NileshPatel17, thank you for this PR. It looks good. For rules migration you can try to use tooling described in this article: https://blog.ninja-squad.com/2021/03/31/migrating-from-tslint-to-eslint/

**Comment by hoebbelsB** [comment]
It just came to my mind... our .spec files are full of comments which disable some tslint rules:

e.g.:
```
// rx-state.service.spec
// tslint:disable-next-line:nx-enforce-module-boundaries
```

@NileshPatel17 would you like to remove all of the comments with that PR as well or should we create a follow up issue after eslint migration for state/cdk/template is finished?

**Comment by edbzn** [comment]
Just merged #1086 based on your commits @NileshPatel17, thanks for the contribution!

**Pull request closed without merging**
