### PR TITLE
fix(template): properly calculate range & anchor when values reset

### LINKED ISSUE #1744: Virtual scroll: Resetting items to an array smaller than currently rendered range results in component crash
# Description

When a virtual scroll has items and is not scrolled to the top, and items get reset to an array smaller than currently rendered, a TypeError is thrown, making a component unusable.

The issue is observed for autosize and dynamic strategies - fixed strategy seems to work just fine.

```
TypeError: Cannot read properties of undefined (reading 'size')
    at _AutoSizeVirtualScrollStrategy.getItemSize (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1942:38)
    at _AutoSizeVirtualScrollStrategy.calcAnchorScrollTop (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1907:36)
    at Object.next (@rx-angular_template_experimental_virtual-scrolling.js?v=dbaf5d77:1620:14)
```

# Steps to Reproduce the Issue

## Reset to empty array

**See stackblitz:**

- [dynamic strategy](https://stackblitz.com/edit/stackblitz-starters-ggjmb8?file=src%2Fmain.ts)
- [autosize strategy](https://stackblitz.com/edit/stackblitz-starters-435szr?file=src%2Fmain.ts)

**Steps:**

1. Enter page
2. Scroll (or click on the "scroll to 100" button)
3. Click on the "reset items" button

**Expected behavior:**

Virtual scroll works just fine and scrolls to the top

**Actual behavior:**

TypeError is thrown and a component is unusable.

## New items array is smaller

It is possible to encounter the issue when new items array is smaller than currently rendered range. See [this stackblitz](https://stackblitz.com/edit/stackblitz-starters-bsuszv?file=src%2Fmain.ts) and follow reproduction steps:

1. Enter page
2. Scroll to the bottom (or click on the "scroll to 5" button)
3. Click on the "set to 1 item" button

**Expected behavior:**

Virtual scroll works just fine and scrolls to the top

**Actual behavior:**

TypeError is thrown and a component is unusable.

# Environment

@rx-angular/template 17+ . Stackblitz has version 18, but in our codebase we observe the same issue with rx-angular version 17.

# Notes

`getItemSize` throws, when an `_virtualItems` array is empty, or an `index` is out of bounds. First part to fix it is probably to add an optional operator. Another part is calling `getItemSize` when `index` is definitely not present there, but I'm not sure how you want to tackle that.

```ts
  getItemSize(index) {
    return this._virtualItems[index]?.size || this.tombstoneSize;
  }
```

### PR DESCRIPTION
**Pull request by hoebbelsB**
# Description

This fix makes sure that the autosize & dynamic size strategies calculate correct values for the new anchorItem & renderedRange. Fixes #1744

### CODE REVIEW

**Review by eneajaho — APPROVED** [review]
LGTM

**Comment by rozpuszczalny** [comment]
Thanks for the fix!

I'm playing around with it (17.3.2 + cherry-picked commit from this PR), and it still yields some errors from time to time. In the attached video, I have 1000 items in the items observable, I click on "scroll to 100", then I generate an empty array, and lastly generate 2 items. After that, an error is generated (see video attached).

For the reproduction setup, see https://github.com/rozpuszczalny/rx-angular/tree/bug/1747-reproduction

[screen-capture (9).webm](https://github.com/user-attachments/assets/a823522f-3a2c-4c51-90b5-406f7b2c73fe)

**Comment by hoebbelsB** [comment]
@rozpuszczalny I knew it was a good idea to wait for your feedback ;). Already figured out the issue. Will fix it by the end of the day! Thanks for sharing

**Comment by hoebbelsB** [comment]
@rozpuszczalny please check again, should be good now :)

**Comment by rozpuszczalny** [comment]
Hey, thanks again for the fix!

This time I had a bit harder time finding more issues, but I wrote a quick monkey test to see if it works fine with quick interactions.

It found one issue that happens after resetting items and then scrolling to a non-existing index. It fails with reading `size` from `undefined`. It happens only for the `autosize` strategy, and for both 17.3.0 + cherry-picked PR and the latest main + cherry-picked PR.

For a reproduction setup, see https://github.com/rozpuszczalny/rx-angular/tree/bug/1747-reproduction-2 . Navigate to the bug page and click on "monkey test from json". You can also play around with monkey test code later on (I encourage to change `maxOpDelay` to low values and `immediateProb` to something closer to 1, so quick interactions, that may induce race conditions occur. Also `generateMonkeyJson` is a bit faulty, as a `scroll` operation is not generating proper values - it can still generate a non-existing index. Yet, for testing purposes it's fine).

```
autosize-virtual-scroll-strategy.ts:983 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'size')
    at AutoSizeVirtualScrollStrategy.getItemSize (autosize-virtual-scroll-strategy.ts:983:38)
    at AutoSizeVirtualScrollStrategy.calcInitialPosition (autosize-virtual-scroll-strategy.ts:945:29)
    at AutoSizeVirtualScrollStrategy.scrollToIndex (autosize-virtual-scroll-strategy.ts:350:30)
    at RxVirtualScrollViewportComponent.scrollToIndex (virtual-scroll-viewport.component.ts:232:25)
    at VirtualForBugComponent.scrollTo (virtual-for-bug.component.ts:230:20)
    at virtual-for-bug.component.ts:211:16
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (asyncToGenerator.js:3:1)
    at _next (asyncToGenerator.js:22:1)
```

**Comment by hoebbelsB** [comment]
oh what a nasty test case :-D I love it! We should put that into the e2e test suite :). Thanks again for the feedback, going to check asap

**Comment by hoebbelsB** [comment]
@rozpuszczalny let's try again? :)

**Comment by rozpuszczalny** [comment]
You bet I will :D

I've generated 50000 ops, with a max delay of 10ms, and an immediate probability of 0.8, and it yielded error below. You can paste slimmed JSON at the end of this comment - simply copy-paste it into the textarea of the monkey test page. Sometimes you need to run a "monkey test from json" multiple times, as it _sometimes_ does work fine. _I presume some race condition occured_

```
reportUnhandledError.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'size')
    at autosize-virtual-scroll-strategy.ts:819:57
    at map.js:7:37
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at takeWhile.js:8:49
    at OperatorSubscriber._next (OperatorSubscriber.js:13:21)
    at OperatorSubscriber.next (Subscriber.js:31:18)
    at Object.next (resize-observer.ts:22:20)
    at ConsumerObserver.next (Subscriber.js:91:33)
    at SafeSubscriber._next (Subscriber.js:60:26)
```

Zrzut ekranu 2024-07-31 115848

<details>
  <summary>Repro JSON</summary>

  ```json
[
    {
        "op": "reset",
        "immediate": true,
        "delay": 0,
        "num": 0
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 3,
        "num": 907
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 9,
        "num": 0
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 9,
        "num": 0
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 8,
        "num": 0
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 9,
        "num": 753
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 5,
        "num": 3470
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 1,
        "num": 0
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 6,
        "num": 505
    },
    {
        "op": "reset",
        "immediate": false,
        "delay": 0,
        "num": 0
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 2,
        "num": 4948
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 6,
        "num": 505
    },
    {
        "op": "scroll",
        "immediate": false,
        "delay": 8,
        "num": 545
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 7,
        "num": 848
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 5,
        "num": 730
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 5,
        "num": 3571
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 9,
        "num": 1934
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 1,
        "num": 1480
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 4,
        "num": 1658
    },
    {
        "op": "reset",
        "immediate": false,
        "delay": 3,
        "num": 0
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 5,
        "num": 3049
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 2,
        "num": 121
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 0,
        "num": 984
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 7,
        "num": 761
    },
    {
        "op": "generate-items",
        "immediate": false,
        "delay": 4,
        "num": 4803
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 1,
        "num": 0
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 1,
        "num": 0
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 3,
        "num": 0
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 1,
        "num": 293
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 0,
        "num": 4082
    },
    {
        "op": "generate-items",
        "immediate": false,
        "delay": 0,
        "num": 4441
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 4,
        "num": 2539
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 1,
        "num": 4725
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 10,
        "num": 3257
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 2,
        "num": 4992
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 1,
        "num": 976
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 6,
        "num": 3981
    },
    {
        "op": "random-scroll",
        "immediate": false,
        "delay": 9,
        "num": 4796
    },
    {
        "op": "scroll",
        "immediate": false,
        "delay": 8,
        "num": 388
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 9,
        "num": 3032
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 7,
        "num": 2050
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 7,
        "num": 66
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 1,
        "num": 3829
    },
    {
        "op": "random-scroll",
        "immediate": true,
        "delay": 1,
        "num": 153
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 8,
        "num": 0
    },
    {
        "op": "reset",
        "immediate": false,
        "delay": 1,
        "num": 0
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 4,
        "num": 117
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 8,
        "num": 0
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 9,
        "num": 779
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 8,
        "num": 0
    },
    {
        "op": "generate-items",
        "immediate": false,
        "delay": 9,
        "num": 471
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 5,
        "num": 0
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 2,
        "num": 0
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 7,
        "num": 2204
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 6,
        "num": 644
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 1,
        "num": 939
    },
    {
        "op": "generate-items",
        "immediate": true,
        "delay": 7,
        "num": 2205
    },
    {
        "op": "reset",
        "immediate": true,
        "delay": 0,
        "num": 0
    },
    {
        "op": "scroll",
        "immediate": true,
        "delay": 5,
        "num": 847
    },
    {
        "op": "reset",
        "immediate": false,
        "delay": 9,
        "num": 0
    }
]
  ```
  
</details>

**Comment by hoebbelsB** [comment]
@rozpuszczalny what about yet another try?

**Comment by rozpuszczalny** [comment]
It's perfect now 😃  Thanks again for taking the effort to fix it 🙌 

One not for a monkey test, I suggest adding this patch to monkey test page, so the `generateMonkeyJson` properly creates `scroll` operation (as `scroll` intention was to scroll to an existing item, and `random-scroll` to either existing item or an item outside the spectrum ;) ) But obviously, it's not affecting the fix, fix works just fine!

<details>
  <summary>Suggested patch</summary>
  
  ```patch
diff --git a/apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-monkey-test.component.ts b/apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-monkey-test.component.ts
index 1cf9b081..2540f5f3 100644
--- a/apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-monkey-test.component.ts
+++ b/apps/demos/src/app/features/template/rx-virtual-for/virtual-rendering/virtual-for-monkey-test.component.ts
@@ -457,6 +457,15 @@ export class VirtualForMonkeyTestComponent {
       delay: number;
     }[] = [];
 
+    ops.push({
+      op: 'generate-items',
+      num: 1000,
+      delay: 1000,
+      immediate: false,
+    });
+
+    let currentItemCount = 1000;
+
     for (let it = 0; it < iterations; it++) {
       const op = operations[Math.floor(Math.random() * operations.length)];
       const immediate = Math.random() < immediateProb;
@@ -464,10 +473,12 @@ export class VirtualForMonkeyTestComponent {
       switch (op) {
         case 'generate-items': {
           const num = Math.round(Math.random() * 5000);
+          currentItemCount = num;
           ops.push({ op, immediate, delay, num });
           break;
         }
         case 'reset':
+          currentItemCount = 0;
           ops.push({ op, immediate, delay, num: 0 });
           break;
         case 'random-scroll': {
@@ -476,7 +487,7 @@ export class VirtualForMonkeyTestComponent {
           break;
         }
         case 'scroll': {
-          const num = Math.round(Math.random() * this.items$.value.length);
+          const num = Math.round(Math.random() * currentItemCount);
           ops.push({ op, immediate, delay, num });
           break;
         }
  ```
  
</details>

**Comment by hoebbelsB** [comment]
thanks for your ongoing support during this journey @rozpuszczalny !

**Pull request merged**
