### PR TITLE
Upgrade to Angular v16

### PR DESCRIPTION
**Pull request by edbzn**
Update Nx and Angular dependencies to v16.

Note: this PR removes the tour-of-heroes-ngxs app as it was consuming old ngxs dependencies that are failing to build since ngcc is removed, I don't think it's very useful to spend time updating this.

### CODE REVIEW

**Review by LcsGa — APPROVED** [review]
Are all the formatting changes wanted?

**Comment by CharlieGreenman** [comment]
Just leaving a comment. I was wondering if this is still being worked on. RxAngular is the one dependency that we have that hasn't been upgraded to 16 yet, and we would be appreciative if this were to be addressed for Angular 16 hydration purposes. Thank you

**Comment by edbzn** [comment]
@CharlieGreenman We are working on it, but most of the required stuff before RxA v16 release is currently wip in #1543.

**Comment by CharlieGreenman** [comment]
thank you

**Pull request merged**
